-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** accountant_view
CREATE VIEW accountant_view as
    select patient_id, patient_name, billing_address, cost from hospital_table;
