-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** BETATEST.Sorting
CREATE OR REPLACE VIEW BETATEST.Sorting

  Comment = 'No Comment Provided'

AS
(
  select 
        FinanceKey as KeyCo1,
        OrganizationKey,
        AccountKey,
        ScenarioKey
  from 
        BETATEST.FactFinance ff

);
