-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** BETATEST.FactFinance
CREATE OR REPLACE TABLE BETATEST.FactFinance
(
 DateKey            number(38,0) NOT NULL,
 OrganizationKey    number(38,0) NOT NULL,
 DepartmentGroupKey number(38,0) NOT NULL,
 ScenarioKey        number(38,0) NOT NULL,
 AccountKey         number(38,0) NOT NULL,
 Amount             float NOT NULL,
 FinanceKey         number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1
)
COMMENT = 'Facts for Finance';
