-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** CENTROIDS_FACT
CREATE VIEW CENTROIDS_FACT as select * from CORP_CENTROIDS_FACT;
