-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


CREATE OR REPLACE FILE FORMAT CsvFileFormat
 TYPE = CSV
 COMPRESSION = BROTLI;
