-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** customers
CREATE OR REPLACE TABLE customers
(
 credit_limit int NOT NULL,
 cust_email   string NOT NULL,
 cust_id      int NOT NULL
);
