-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** "dbo"."Customer"
CREATE TABLE "dbo"."Customer"
(
 "CustomerId"   int NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 "CustomerName" varchar(80) NOT NULL,
 "Phone"        varchar(40),
 CONSTRAINT "PK_Customer" PRIMARY KEY ( "CustomerId" ),
 CONSTRAINT "AK1_Customer_CustomerName" UNIQUE ( "CustomerName" )
)
CLUSTER BY ( "CustomerId" )
COMMENT = 'Basic information 
about Customer';
