-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** "dbo"."Supplier"
CREATE TABLE "dbo"."Supplier"
(
 "SupplierId"  int NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 "CompanyName" varchar(80) NOT NULL,
 "Phone"       varchar(40),
 CONSTRAINT "PK_Supplier" PRIMARY KEY ( "SupplierId" ),
 CONSTRAINT "AK1_Supplier_CompanyName" UNIQUE ( "CompanyName" )
)
CLUSTER BY ( "SupplierId" )
COMMENT = 'Basic information 
about Supplier';
