-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** "dbo"."OrderItem"
CREATE TABLE "dbo"."OrderItem"
(
 "OrderId"   int NOT NULL,
 "ProductId" int NOT NULL,
 "UnitPrice" decimal(12,2) NOT NULL,
 "Quantity"  int NOT NULL,
 CONSTRAINT "PK_OrderItem" PRIMARY KEY ( "OrderId", "ProductId" ),
 CONSTRAINT "FK_OrderItem_OrderId_Order" FOREIGN KEY ( "OrderId" ) REFERENCES "dbo"."Order" ( "OrderId" ),
 CONSTRAINT "FK_OrderItem_ProductId_Product" FOREIGN KEY ( "ProductId" ) REFERENCES "dbo"."Product" ( "ProductId" )
)
CLUSTER BY ( "OrderId", "ProductId" )
COMMENT = 'Information about
like Price, Quantity';
