-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** "dbo"."Order"
CREATE TABLE "dbo"."Order"
(
 "OrderId"     int NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 "OrderNumber" varchar(20),
 "CustomerId"  int NOT NULL,
 "OrderDate"   datetime NOT NULL DEFAULT (getdate()),
 "TotalAmount" decimal(12,2) NOT NULL,
 CONSTRAINT "PK_Order" PRIMARY KEY ( "OrderId" ),
 CONSTRAINT "AK1_Order_OrderNumber" UNIQUE ( "OrderNumber" ),
 CONSTRAINT "FK_Order_CustomerId_Customer" FOREIGN KEY ( "CustomerId" ) REFERENCES "dbo"."Customer" ( "CustomerId" )
)
CLUSTER BY ( "OrderId" )
COMMENT = 'Order information
like Date, Amount';
