-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** "dbo"."Product"
CREATE TABLE "dbo"."Product"
(
 "ProductId"      int NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 "ProductName"    varchar(100) NOT NULL,
 "SupplierId"     int NOT NULL,
 "UnitPrice"      decimal(12,2),
 "IsDiscontinued" boolean NOT NULL DEFAULT ((0)),
 CONSTRAINT "PK_Product" PRIMARY KEY ( "ProductId" ),
 CONSTRAINT "AK1_Product_SupplierId_ProductName" UNIQUE ( "SupplierId", "ProductName" ),
 CONSTRAINT "FK_Product_SupplierId_Supplier" FOREIGN KEY ( "SupplierId" ) REFERENCES "dbo"."Supplier" ( "SupplierId" )
)
CLUSTER BY ( "ProductId" )
COMMENT = 'Basic information 
about Product';
