-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** department
CREATE OR REPLACE TABLE department
(
 dep_id    integer,
 dep_title varchar
);
