-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** Dim_Product
CREATE TABLE Dim_Product
(
 ProductId   int NOT NULL,
 ProductName string NOT NULL,
 CONSTRAINT PK_Product PRIMARY KEY ( ProductId )
)
STAGE_FILE_FORMAT = 
(
 TYPE = JSON
);
