-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** DISPOSAL_TURN_TIMES_MA_VW
CREATE VIEW DISPOSAL_TURN_TIMES_MA_VW as 
SELECT A.MA_ID MA_ID , DISPFAC_TYPE, AVG(NET_TURN_TIME) TURN_TIME 
FROM MART.DISPOSAL_TURN_TIMES_SITE_MA_LEVEL_VW  A
GROUP BY A.MA_ID, DISPFAC_TYPE
;
