-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** doctor_view
CREATE VIEW doctor_view as
    select patient_id, patient_name, diagnosis, treatment from hospital_table;
