-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** doctors
CREATE OR REPLACE VIEW doctors as 
  select name, dep_title
  from employees emp JOIN department dep
  on emp.dep_id = dep.id
  where emp.title = 'doctor';
