-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** emp_view
CREATE OR REPLACE VIEW emp_view as select id "Employee Number", lname "Last Name", location "Home Base" from emp;
