-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** employees
CREATE OR REPLACE TABLE employees
(
 id     integer,
 name   varchar,
 title  varchar,
 dep_id integer
);
