-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** employee_hierarchy
CREATE OR REPLACE VIEW employee_hierarchy (title, employee_id, manager_id, "MGR_EMP_ID (SHOULD BE SAME)", "MGR TITLE") as (
   with recursive employee_hierarchy_cte (title, employee_id, manager_id, "MGR_EMP_ID (SHOULD BE SAME)", "MGR TITLE") as (
      -- Start at the top of the hierarchy ...
      select title, employee_id, manager_id, null as "MGR_EMP_ID (SHOULD BE SAME)", 'President' as "MGR TITLE"
        from employees
        where title = 'President'
      union all
      -- ... and work our way down one level at a time.
      select employees.title, 
             employees.employee_id, 
             employees.manager_id, 
             employee_hierarchy_cte.employee_id as "MGR_EMP_ID (SHOULD BE SAME)", 
             employee_hierarchy_cte.title as "MGR TITLE"
        from employees inner join employee_hierarchy_cte
       where employee_hierarchy_cte.employee_id = employees.manager_id
   )
   select * 
      from employee_hierarchy_cte
);
