-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** EMPLOYEE_JSON_VW
CREATE OR REPLACE VIEW EMPLOYEE_JSON_VW
AS
WITH NEW
AS (SELECT OBJECT_CONSTRUCT('EMPLOYEE_LIST', ARRAY_AGG(OBJECT_CONSTRUCT('EMP_ID',EMP_ID,'EMP_NAME',EMP_NAME,'EMP_ADDRESS',EMP_ADDRESS)))
FROM EMPLOYEE)
SELECT * FROM NEW;
