-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** IA_POWERBI.Base
CREATE OR REPLACE VIEW DWH_DEV2.IA_POWERBI.Base Accounts Receivable"

(
 
"Accounts Receivable Key",
 
"Company Key",
 
"Customer Key",
 
"Currency Key TCY",
 
"Currency Key LCY",
 
"Payment Term Key",
 
"Employee CDM Key",
 
"Date Transaction",
 
"Date Due",
 
"Date Settled",
 
"Date Closed",
 
"Date Document",
 
"Voucher",
 
"Invoice Number",
 
"Amount TCY",
 
"Amount LCY",
 
"Date Exchangerate RCY",
 
"Type Exchangerate RCY",
 
"Source Exchangerate RCY",
 
"BA Source Table",
 
"Load timestamp"
 
) as
 

 
WITH BASE AS (
 
SELECT
 
a.accountsreceivable_key || '#initial' AS "Accounts Receivable Key"
 
, a.company_key AS "Company Key"
 
, a.customer_key AS "Customer Key"
 
, a.currency_key_tcy AS "Currency Key TCY"
 
, a.currency_key_lcy AS "Currency Key LCY"
 
, a.paymentterm_key AS "Payment Term Key"
 
, c.employee_key_customer_development_manager AS "Employee CDM Key"
 
, a.date_transaction AS "Date Transaction"
 
, a.date_due AS "Date Due"
 
, a.date_closed AS "Date Closed"
 
, a.date_document AS "Date Document"
 
, a.voucher AS "Voucher"
 
, a.invoice_number AS "Invoice Number"
 
, a.amount_tcy AS "Amount TCY"
 
, a.amount_lcy AS "Amount LCY"
 
, a.date_exchangerate_rcy AS "Date Exchangerate RCY"
 
, a.type_exchangerate_rcy AS "Type Exchangerate RCY"
 
, a.source_exchangerate_rcy AS "Source Exchangerate RCY"
 
, 'BA Accounts Receivable' AS "BA Source Table"
 
, a.ta_update_datetime AS "Load timestamp"
 
FROM ba.ba_accountsreceivable a
 
LEFT JOIN ba.bv_customer c
 
ON a.customer_key = c.customer_key
 
AND c.ea_actual_flag = 1
 
WHERE a.ta_status_code = 2
 

 
UNION ALL
 

 
--Subtract all settled transactions (-1 * settled amount)
 
SELECT
 
s.salesordersettlement_key || '#settlement' AS "Accounts Receivable Key"
 
, a.company_key AS "Company Key"
 
, a.customer_key AS "Customer Key"
 
, a.currency_key_tcy AS "Currency Key TCY"
 
, s.currency_key_lcy AS "Currency Key LCY"
 
, a.paymentterm_key AS "Payment Term Key"
 
, c.employee_key_customer_development_manager AS "Employee CDM Key"
 
, s.date_transaction AS "Date Transaction"
 
, NULL AS "Date Due"
 
, NULL AS "Date Closed"
 
, NULL AS "Date Document"
 
, s.voucher AS "Voucher"
 
, a.invoice_number AS "Invoice Number"
 
, -1 * s.amount_settled_tcy AS "Amount TCY"
 
, -1 * s.amount_settled_lcy AS "Amount LCY"
 
, s.date_exchangerate_rcy AS "Date Exchangerate RCY"
 
, s.type_exchangerate_rcy AS "Type Exchangerate RCY"
 
, s.source_exchangerate_rcy AS "Source Exchangerate RCY"
 
, 'BA Sales Order Settlement' AS "BA Source Table"
 
, s.ta_update_datetime AS "Load timestamp"
 
FROM ba.ba_salesordersettlement s
 
LEFT JOIN ba.ba_accountsreceivable a
 
ON s.accountsreceivable_key = a.accountsreceivable_key
 
AND a.ta_status_code = 2
 
LEFT JOIN ba.bv_customer c
 
ON a.customer_key = c.customer_key
 
AND c.ea_actual_flag = 1
 
WHERE s.ta_status_code = 2
 

 
UNION ALL
 

 
--Add all settlement adjustments
 
--These FX adjustments have a TCY amount of 0 and are of voucher type SPV or SFX
 
SELECT
 
s.salesordersettlement_key || '#adjustment' AS "Accounts Receivable Key"
 
, s.company_key AS "Company Key"
 
, a.customer_key AS "Customer Key"
 
, s.currency_key_tcy AS "Currency Key TCY"
 
, s.currency_key_lcy AS "Currency Key LCY"
 
, a.paymentterm_key AS "Payment Term Key"
 
, c.employee_key_customer_development_manager AS "Employee CDM Key"
 
, s.date_transaction AS "Date Transaction"
 
, NULL AS "Date Due"
 
, NULL AS "Date Closed"
 
, NULL AS "Date Document"
 
, s.voucher_offset_transaction AS "Voucher"
 
, a.invoice_number AS "Invoice Number"
 
, s.amount_settled_tcy AS "Amount TCY"
 
, s.amount_settled_lcy AS "Amount LCY"
 
, s.date_exchangerate_rcy AS "Date Exchangerate RCY"
 
, s.type_exchangerate_rcy AS "Type Exchangerate RCY"
 
, s.source_exchangerate_rcy AS "Source Exchangerate RCY"
 
, 'BA Sales Order Settlement' AS "BA Source Table"
 
, s.ta_update_datetime AS "Load timestamp"
 
FROM ba.ba_salesordersettlement s
 
LEFT JOIN ba.ba_accountsreceivable a
 
ON s.accountsreceivable_key = a.accountsreceivable_key
 
AND a.ta_status_code = 2
 
LEFT JOIN ba.bv_customer c
 
ON a.customer_key = c.customer_key
 
AND c.ea_actual_flag = 1
 
WHERE s.ta_status_code = 2
 
AND s.amount_settled_tcy = 0
 
AND UPPER(LEFT(s.voucher, 3)) IN ('SPV', 'SFX')
 
),
 
CTE AS (
 
SELECT
 
"Accounts Receivable Key" AS "Accounts Receivable Key"
 
, MAX("Date Due") OVER (PARTITION BY "Company Key", "Customer Key", "Voucher" ORDER BY "Date Due" ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS Option1
 
, MAX("Date Due") OVER (PARTITION BY "Company Key", "Customer Key", "Invoice Number" ORDER BY "Date Due" ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS Option2
 
, SUM("Amount LCY") OVER (PARTITION BY "Company Key", "Customer Key", "Voucher" ORDER BY "Date Due" ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS AmountSettled
 
, MAX("Date Transaction") OVER (PARTITION BY "Company Key", "Customer Key", "Voucher" ORDER BY "Date Transaction" ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS DateSettled
 
FROM BASE
 
)
 
SELECT
 
BASE."Accounts Receivable Key"
 
, BASE."Company Key"
 
, BASE."Customer Key"
 
, BASE."Currency Key TCY"
 
, BASE."Currency Key LCY"
 
, BASE."Payment Term Key"
 
, BASE."Employee CDM Key"
 
, BASE."Date Transaction"
 
, CASE
 
WHEN BASE."Date Due" IS NOT NULL AND BASE."Date Due" != '1900-01-01' THEN BASE."Date Due"
 
WHEN (BASE."Date Due" IS NULL OR BASE."Date Due" = '1900-01-01') AND CTE.Option1 IS NOT NULL AND CTE.Option1 != '1900-01-01' THEN CTE.Option1
 
WHEN (BASE."Date Due" IS NULL OR BASE."Date Due" = '1900-01-01') AND (CTE.Option1 IS NULL OR CTE.Option1 = '1900-01-01') AND CTE.Option2 IS NOT NULL AND CTE.Option2 != '1900-01-01' THEN CTE.OPTION2
 
ELSE BASE."Date Transaction"
 
END AS "Date Due"
 
, CASE
 
WHEN CTE.AmountSettled = 0 AND BASE."Date Transaction" = CTE.DateSettled THEN CTE.DateSettled
 
ELSE NULL
 
END AS "Date Settled"
 
, "Date Closed"
 
, "Date Document"
 
, "Voucher"
 
, "Invoice Number"
 
, "Amount TCY"
 
, "Amount LCY"
 
, "Date Exchangerate RCY"
 
, "Type Exchangerate RCY"
 
, "Source Exchangerate RCY"
 
, "BA Source Table"
 
, "Load timestamp"
 
FROM BASE
 
LEFT JOIN CTE
 
ON CTE."Accounts Receivable Key" = BASE."Accounts Receivable Key";
