-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


CREATE OR REPLACE FILE FORMAT InlineJsonFileFormat
 TYPE = JSON;
