-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** jofmi_ds
CREATE OR REPLACE TABLE jofmi_ds
(
 id     integer,
 name   varchar,
 title  varchar,
 dep_id integer
);
