-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** jofmi_dep
CREATE OR REPLACE TABLE jofmi_dep
(
 dep_id    integer,
 dep_title varchar
);
