-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** jomi_d_hierarchy
CREATE OR REPLACE VIEW jomi_d_hierarchy (title, jomi_d_id, manager_id, "MGR_EMP_ID (SHOULD BE SAME)", "MGR TITLE") as (
   with recursive jomi_d_hierarchy_cte (title, jomi_d_id, manager_id, "MGR_EMP_ID (SHOULD BE SAME)", "MGR TITLE") as (
      -- Start at the top of the hierarchy ...
      select title, jomi_d_id, manager_id, null as "MGR_EMP_ID (SHOULD BE SAME)", 'President' as "MGR TITLE"
        from jomi_ds
        where title = 'President'
      union all
      -- ... and work our way down one level at a time.
      select jomi_ds.title, 
             jomi_ds.jomi_d_id, 
             jomi_ds.manager_id, 
             jomi_d_hierarchy_cte.jomi_d_id as "MGR_EMP_ID (SHOULD BE SAME)", 
             jomi_d_hierarchy_cte.title as "MGR TITLE"
        from jomi_ds inner join jomi_d_hierarchy_cte
       where jomi_d_hierarchy_cte.jomi_d_id = jomi_ds.manager_id
   )
   select * 
      from jomi_d_hierarchy_cte
);
