-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** jomi_ds
CREATE OR REPLACE TABLE jomi_ds
(
 title      varchar,
 jomi_d_id  integer,
 manager_id integer
);
