-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


sdf
select
PKEY,
substring(FAC_ID,1,6) as FAC_ID,
CASE when substring(FAC_ID,8) = 'TS' then 'Transfer Station'
   when substring(FAC_ID,8) = 'MRF' then 'MRF Recycling' else
              substring(FAC_ID,8) end  as FAC_TYPE,
MIN_TONS,
MAX_TONS,
VOLUME_CONSTRAINT_TYPE,
VOLUME_TIME_UNIT,
NOTES,
LAST_UPDATED_DTM,
LAST_UPDATED_USER
from DISPOSAL_SITE_CONSTRAINTS;
