-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** LH_LIST_LOB
CREATE VIEW LH_LIST_LOB as

select  'COMMERCIAL' LOB union all

select  'RESIDENTIAL' LOB union all

select  'ROLLOFF';
