-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** LH_LIST_WASTE_ACCEPTED_FLAG
CREATE VIEW LH_LIST_WASTE_ACCEPTED_FLAG

as select 'Y' as ACCEPTED_FLAG, 'Accepted' as ACCEPTED_FLAG_DESC union all 

          select 'N' , 'No' union all 

          select 'U' , 'Unknown';
