-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** LH_LIST_MA
CREATE VIEW LH_LIST_MA as

select * from LH_LIST_HAULING_SITE_MA

union

select * from MART.LH_LIST_DISPOSAL_SITE_MA;
