-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** LOCATION_MATCHING
CREATE VIEW LOCATION_MATCHING as select * from BMT_LOCATION_MATCHING

where nvl(DATA_COLLCTION_ADD_DELETE_UPDATE,'A') != 'D';
