-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** medium_orders
CREATE OR REPLACE VIEW medium_orders

  Comment = 'No Comment Provided'

AS Select order_id, credit_limit from orders, customers where customers.cust_id = orders.customer_id and order_total > 100;
