-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** medical_staff
CREATE OR REPLACE VIEW medical_staff as
    select * from doctoe_fff
    union
    select * from nurses_es;
