-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** MODEL_DEPOT_LOB
CREATE VIEW MODEL_DEPOT_LOB as

select

  mcp.depotfacid as FAC_ID,

  mcp.SUBLOB,

  VEHICLE_COST_PER_HOUR as COSTS_PER_HOUR,

  5 as CUT_OFF_TIME_HOURS                     from

    (select distinct depotfacid, LOB, SUBLOB from MODEL_COLLECTION_POINTS ) mcp

    left join HAULING_SITE_CAPACITY hs

on substring(mcp.depotfacid,1,6) = hs.fac_id and mcp.SUBLOB = hs.SUBLOB;
