-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** MODEL_SWAP_DETAIL
CREATE VIEW MODEL_SWAP_DETAIL as

SELECT 21 AS SWAP_HEADER_ID, 'BFI_SWAP' as SWAP_NAME, 'S01000' AS DEPOT_FAC_ID, 'S02000' as DISP_FAC_ID, null as LOB, 'MSW' as WASTE_TYPE where 0=1;
