-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** myview1
CREATE OR REPLACE SECURE VIEW myview1 comment='Test secure view' as select col1, col2 from mytable;
