-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** Myview_123
CREATE OR REPLACE SECURE VIEW Myview_123 comment='Test secure view' as select * from table_123;
