-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** myview2
CREATE OR REPLACE VIEW myview2
as select * 
    from employee_hierarchy 
    order by employee_id;
