-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** myview
CREATE OR REPLACE SECURE VIEW myview comment='Test secure view' as select col1, col2 from mytable;
