-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** nurses_es
CREATE OR REPLACE VIEW nurses_es as 
  select name, dep_title
  from jofmi_ds emp JOIN jofmi_dep dep
  on emp.dep_id = dep.id
  where emp.title = 'nurse';
