-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** orders
CREATE OR REPLACE TABLE orders
(
 order_id     int NOT NULL,
 customer_id  bigint NOT NULL,
 order_total  bigint NOT NULL,
 sales_rep_id string NOT NULL
);
