-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** Product_444
CREATE OR REPLACE TABLE Product_444
(
 id         int NOT NULL,
 name       varchar NOT NULL,
 category   varchar NOT NULL,
 unit_price decimal NOT NULL
);
