-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** Products_444_sold
CREATE OR REPLACE TABLE Products_444_sold
(
 product_id int NOT NULL,
 sold_value decimal NOT NULL
);
