-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** sample_view
CREATE OR REPLACE VIEW sample_view
AS
  SELECT source_id,
         source_name
  FROM   rec_test
  WHERE  source_id = $where_c;
