-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** sc_test11
CREATE VIEW sc_test11
as
select 'County' as SRC;
