-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** stg.FACILITY_LOCATION_CONSTRAINTS_DATA_BMT_DATA_COLLCTN
CREATE OR REPLACE TABLE stg.FACILITY_LOCATION_CONSTRAINTS_DATA_BMT_DATA_COLLCTN
(
 LAST_UPDATED_DTM                 int,
 MIN_TONS                         varchar,
 VOLUME_CONSTRAINT_TYPE           int,
 FAC_TYPE                         int,
 MAX_TONS                         int,
 NOTES                            int,
 LAST_UPDATED_USER                int,
 VOLUME_TIME_UNIT                 int,
 FAC_ID                           int,
 PKEY                             int,
 DATA_COLLCTION_ADD_DELETE_UPDATE int
);
