-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** SWAP_HEADER
CREATE VIEW SWAP_HEADER as 

SELECT 1 AS SWAP_HEADER_ID, 'BFI_SWAP' as SWAP_NAME, 20000 as SWAP_QTY, 999999 as SHORTFALL_PENALTY_PER_TON, 999999 as SHORTFALL_PENALTY_REPORT;
