-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** table_123
CREATE OR REPLACE TABLE table_123
(

);
