-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** [table_29_copy_13_copy_2_copy_2_copy_1]
IF NOT EXISTS (SELECT * FROM sys.tables t WHERE t.name='table_29_copy_13_copy_2_copy_2_copy_1')
CREATE TABLE [table_29_copy_13_copy_2_copy_2_copy_1]
(
 [col_4]                                                       int NOT NULL ,
 [col_4_1]                                                     int NOT NULL ,
 [col_4_2]                                                     int NOT NULL ,
 [col_4_4343434f34f34f34f34f34f34f34f34f34f34f34f34f34f34f34f] smallint NOT NULL ,
 [col_4_5]                                                     int NOT NULL ,
 [col_4_6]                                                     smallint NOT NULL ,
 [col_4_7]                                                     int NOT NULL ,
 [col_4_8]                                                     int NOT NULL ,
 [col_4_9]                                                     int NOT NULL ,
 [col_4_10]                                                    int NOT NULL ,
 [col_4_11]                                                    int NOT NULL ,
 [col_4_12]                                                    int NOT NULL ,
 [col_4_13]                                                    int NOT NULL ,
 [col_4_14]                                                    int NOT NULL ,
 [col_4_15]                                                    int NOT NULL ,
 [col_4_16]                                                    int NOT NULL ,
 [col_4_17]                                                    int NOT NULL ,
 [col_4_2_1]                                                   int NOT NULL ,
 [col_4_2_2]                                                   int NOT NULL ,
 [col_4_2_3]                                                   int NOT NULL ,
 [col_4_2_4]                                                   int NOT NULL 

);
GO