-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** TEST_VIEW1
CREATE OR REPLACE VIEW TEST_VIEW1
AS SELECT                             
COL1,                               
COL2,                               
DATA1:Facebook::STRING AS Facebook, 
DATA1:Icon::STRING AS Icon,         
DATA1:URL::STRING AS URL,           
DATA2:k1::STRING AS k1,             
DATA2:k2::STRING AS k2,             
DATA2:k3::STRING AS k3,             
DATA1:Twitter::STRING AS Twitter,   
DATA2:k4::STRING AS k4              
FROM TEST2;
