-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** test
CREATE VIEW test as select * from model_hrs_cap;
