-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** TIME_HORIZON
CREATE VIEW TIME_HORIZON as

select 'Daily' TIME_HORIZON_NM

union all select 'Monthly'

union all select 'Quarterly'

union all select 'Yearly';
