-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** top_10_products_v
CREATE OR REPLACE VIEW top_10_products_v as
select 
  top_10 p.name, 
  p.category, 
  p.unit_price, 
  ps.quantity_sold, 
  p.unit_price * ps.quantity_sold as sold_value
from Product_444 p
left join Products_444_sold ps on p.id = ps.product_id
order by sold_value desc;
