-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** TST_FLOW_CONTROL
CREATE VIEW TST_FLOW_CONTROL as select * from TST_BMT_FLOW_CONTROL
where nvl(DATA_COLLCTION_ADD_DELETE_UPDATE,'A') != 'D';
