-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** view_2
CREATE OR REPLACE VIEW view_2 
as
select * 
    from employee_hierarchy 
    order by employee_id;
