-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** view_name1
CREATE OR REPLACE VIEW view_name1 (alias_1, alias_2) AS
SELECT col_1 as 'Employee Name', 
col_2 as 'alias_3'
FROM table
WHERE col_3 > 2;
