-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** view_2284
creste view view3 as
select * from table2 (information_schema.materialized_view_refresh_history());
