-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** view_367
CREATE OR REPLACE VIEW view_367

  Comment = 'No Comment Provided'

AS
select * from betatest.Sorting;
