-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** view_2505
creste view v4 as
select * from t2 (information_schema.materialized_view_refresh_history());
