-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** view_1
CREATE OR REPLACE VIEW view_1 (alias_1, alias_2) AS
 SELECT col_1, col_2
 FROM table1
 WHERE col_3 > 2;
